# Generated by Django 4.0.5 on 2022-06-17 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_category', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='apilist',
            name='parent_api_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.apicategory'),
        ),
        migrations.AddField(
            model_name='apinote',
            name='parent_api_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.apicategory'),
        ),
    ]
