# Generated by Django 4.0.5 on 2022-06-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apicategory_apilist_parent_api_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apinote',
            name='content',
            field=models.TextField(max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='apinote',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
