# Generated by Django 4.0.5 on 2022-07-01 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_apinote_content_alter_apinote_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilistitem',
            name='parent_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.apilist'),
        ),
    ]
