# Generated by Django 4.0.5 on 2022-07-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_apilistitem_parent_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilist',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
