# Generated by Django 4.0.5 on 2022-07-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_apilist_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilistitem',
            name='item',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
