# Generated by Django 4.0.5 on 2022-07-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_apilistitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilistitem',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
